name: Publish package to npmjs when release (tag) is created
on:
  release:
    types: [published] # A release without a binary is a 'tag' rather than a release

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - run: |
          git config user.name jonw-cogapp
          git config user.email jonw@cogapp.com

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Create new version
        run: |
          TAG_NAME="${GITHUB_REF##*/}"
          npm version "$TAG_NAME"
          git push

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
